# Primitive integer and identifier expressions.
#
123
Hello
b32

# Multiplicative expressions.
#
a * 123
12 / -b

# Additive expressions.
#
a + b*123
12*-2 - b*4 + c/3

# Relational expressions.
#
a > b + 1
13 <= b*2


# Parenthesized expressions.
#
(a - 2) * 3
4 / (b + -c + d)

# Top-level unary minus expressions.
#
(-- 123)

# Conditional expressions.
#
(a < b ? a : b + c)


# Function call expressions.
#
f()
f(a + b, -c, 3*d)


# Function definitions.
#
def f(a, b) a + b
def MAGIC() 7

